##########################
Flowers.png:
  OUTPUT_SIZE: 32
  N : 3
  VISUALIZE_ENCODE: False
  VISUALIZE_ADJACENCY: False
  WRITE : False
  WRITE_VIDEO : True
  GROUND : True
  MAX_BACKTRACK : 20
  GROUND_LEVEL : 19
  MODE : "overlap"
##########################

  